# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesLiga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamranks',
            old_name='еqual',
            new_name='еqual1',
        ),
    ]
